
# run the curve_fitting_well script before this one !!!!!!
# we are gonna use the residual_data dataset to calculate the r squared 

# add the sample column into the residual_data dataset

df <- read_csv("data/tidydata/joined_15P_update.csv") %>%
  select(Well, Sample) %>%
  unique()

residual_data <- left_join(residual_data, df)

#### R2 for test samples ####

# calculate the r-squared for each well sample (MAGIC population)

rs1 <- residual_data %>%
  filter(Sample != "C+" & Sample != "C-") 

rs1 <- rs1 %>%
  group_by(Well) %>%
  mutate(rss = sum((HE - .fitted) ^ 2),
         # calculate the residual sum of squares (rss)
         tss = sum((HE - mean(HE)) ^ 2),
         # calculate the total sum of squares (tss)
         r_squared = 1 - rss/tss,
         adj_r2 = 1 - (1 - r_squared)*8/6,
         rmse = sqrt(rss/9),
         rse = sqrt(rss/6)) %>%
  ungroup()
# calculate the average r-squared for all samples (MAGIC population)

rs1 %>%
  summarise(mean_rs = mean(r_squared, na.rm = TRUE),
            sd_rs = sd(r_squared, na.rm = TRUE),
            mean_ajdr2 = mean(adj_r2, na.rm = TRUE),
            sd_adjr2 = sd(adj_r2, na.rm = TRUE),
            mean_rmse = mean(rmse, na.rm = TRUE),
            sd_rmse = sd(rmse, na.rm = TRUE),
            mean_rse = mean(rse, na.rm = TRUE),
            sd_rse = sd(rse, na.rm = TRUE))
# r-squared -> mean = 0.997, sd = 0.00231
# adj r-squared -> mean = 0.996, sd = 0.00308
# rmse -> mean = 1.26, sd = 0.505
# rse -> mean = 1.54, sd = 0.618

#### R2 for positive controls ####

# calculate the r-squared for each well sample (MAGIC population)

rs2 <- residual_data %>%
  filter(Sample == "C+") 

rs2 <- rs2 %>%
  group_by(Well) %>%
  mutate(rss = sum((HE - .fitted) ^ 2),
         # calculate the residual sum of squares (rss)
         tss = sum((HE - mean(HE)) ^ 2),
         # calculate the total sum of squares (tss)
         r_squared = 1 - rss/tss,
         adj_r2 = 1 - (1 - r_squared)*8/6,
         rmse = sqrt(rss/9),
         rse = sqrt(rss/6)) %>%
  ungroup()

# calculate the average r-squared for all samples (MAGIC population)

rs2 %>%
  summarise(mean_rs = mean(r_squared, na.rm = TRUE),
            sd = sd(r_squared, na.rm = TRUE),
            mean_ajdr2 = mean(adj_r2, na.rm = TRUE),
            sd_adjr2 = sd(adj_r2, na.rm = TRUE),
            mean_rmse = mean(rmse, na.rm = TRUE),
            sd_rmse = sd(rmse, na.rm = TRUE),
            mean_rse = mean(rse, na.rm = TRUE),
            sd_rse = sd(rse, na.rm = TRUE)) 
# r-square -> mean = 0.992, sd = 0.00580
# adj r-square -> mean = 0.989, sd = 0.00773
# rmse -> mean = 2.55, sd = 1.06
# rse -> mean = 3.13, sd = 1.30

#### R2 for negative controls ####

# calculate the r-squared for each well sample (MAGIC population)

rs3 <- residual_data %>%
  filter(Sample == "C-") %>%
  group_by(Well) %>%
  mutate(rss = sum((HE - .fitted) ^ 2),
         # calculate the residual sum of squares (rss)
         tss = sum((HE - mean(HE)) ^ 2),
         # calculate the total sum of squares (tss)
         r_squared = 1 - rss/tss,
         adj_r2 = 1 - (1 - r_squared)*8/6,
         rmse = sqrt(rss/9),
         rse = sqrt(rss/6)) %>%
  ungroup()

# calculate the average r-squared for all samples (MAGIC population)

rs3 %>%
  summarise(mean_rs = mean(r_squared, na.rm = TRUE),
            sd = sd(r_squared, na.rm = TRUE),
            mean_ajdr2 = mean(adj_r2, na.rm = TRUE),
            sd_adjr2 = sd(adj_r2, na.rm = TRUE),
            mean_rmse = mean(rmse, na.rm = TRUE),
            sd_rmse = sd(rmse, na.rm = TRUE),
            mean_rse = mean(rse, na.rm = TRUE),
            sd_rse = sd(rse, na.rm = TRUE))
# r-square -> mean = 0.990, sd = 0.00533
# adj r-square -> mean = 0.986, sd = 0.00711
# rmse -> mean = 1.85, sd = 0.424
# rse -> mean = 2.26, sd = 0.519

# IMPORTANT NOTES below
# note that the rse calculated by myself is not completely equals to the value 
# generated by R itself, but very close. In the CSI report, I'll use the RSE
# generated by R