
# run the curve_fitting_well script before this one !!!!!!
# we are gonna use the residual_data dataset to calculate the r squared 

# add the sample column into the residual_data dataset

df <- read_csv("data/tidydata/joined_15P_update.csv") %>%
  select(Well, Sample) %>%
  unique()

residual_data <- left_join(residual_data, df)

#### R2 for test samples ####

# calculate the r-squared for each well sample (MAGIC population)

rs1 <- residual_data %>%
  filter(Sample != "C+" & Sample != "C-") 

rs1 <- rs1 %>%
  group_by(Well) %>%
  mutate(rss = sum((HE - .fitted) ^ 2),
         # calculate the residual sum of squares (rss)
         tss = sum((HE - mean(HE)) ^ 2),
         # calculate the total sum of squares (tss)
         r_squared = 1 - rss/tss,
         adj_r2 = 1 - (1 - r_squared)*8/5,
         rmse = sqrt(rss/9),
         rse = sqrt(rss/5)) %>%
  ungroup()
# calculate the average r-squared for all samples (MAGIC population)

rs1 %>%
  summarise(mean_rs = mean(r_squared, na.rm = TRUE),
            sd_rs = sd(r_squared, na.rm = TRUE),
            mean_ajdr2 = mean(adj_r2, na.rm = TRUE),
            sd_adjr2 = sd(adj_r2, na.rm = TRUE),
            mean_rmse = mean(rmse, na.rm = TRUE),
            sd_rmse = sd(rmse, na.rm = TRUE),
            mean_rse = mean(rse, na.rm = TRUE),
            sd_rse = sd(rse, na.rm = TRUE))
# r-squared -> mean = 0.998, sd = 0.00225
# adj r-squared -> mean = 0.996, sd = 0.00360
# rmse -> mean = 1.02, sd = 0.462
# rse -> mean = 1.37, sd = 0.62

#### R2 for positive controls ####

# calculate the r-squared for each well sample (MAGIC population)

rs2 <- residual_data %>%
  filter(Sample == "C+") 

rs2 <- rs2 %>%
  group_by(Well) %>%
  mutate(rss = sum((HE - .fitted) ^ 2),
         # calculate the residual sum of squares (rss)
         tss = sum((HE - mean(HE)) ^ 2),
         # calculate the total sum of squares (tss)
         r_squared = 1 - rss/tss,
         adj_r2 = 1 - (1 - r_squared)*8/5,
         rmse = sqrt(rss/9),
         rse = sqrt(rss/5)) %>%
  ungroup()

# calculate the average r-squared for all samples (MAGIC population)

rs2 %>%
  summarise(mean_rs = mean(r_squared, na.rm = TRUE),
            sd = sd(r_squared, na.rm = TRUE),
            mean_ajdr2 = mean(adj_r2, na.rm = TRUE),
            sd_adjr2 = sd(adj_r2, na.rm = TRUE),
            mean_rmse = mean(rmse, na.rm = TRUE),
            sd_rmse = sd(rmse, na.rm = TRUE),
            mean_rse = mean(rse, na.rm = TRUE),
            sd_rse = sd(rse, na.rm = TRUE)) 
# r-square -> mean = 0.995, sd = 0.00307
# adj r-square -> mean = 0.992, sd = 0.00491
# rmse -> mean = 1.65, sd = 0.599
# rse -> mean = 2.22, sd = 0.804

#### R2 for negative controls ####

# calculate the r-squared for each well sample (MAGIC population)

rs3 <- residual_data %>%
  filter(Sample == "C-") %>%
  group_by(Well) %>%
  mutate(rss = sum((HE - .fitted) ^ 2),
         # calculate the residual sum of squares (rss)
         tss = sum((HE - mean(HE)) ^ 2),
         # calculate the total sum of squares (tss)
         r_squared = 1 - rss/tss,
         adj_r2 = 1 - (1 - r_squared)*8/5,
         rmse = sqrt(rss/9),
         rse = sqrt(rss/5)) %>%
  ungroup()

# calculate the average r-squared for all samples (MAGIC population)

rs3 %>%
  summarise(mean_rs = mean(r_squared, na.rm = TRUE),
            sd = sd(r_squared, na.rm = TRUE),
            mean_ajdr2 = mean(adj_r2, na.rm = TRUE),
            sd_adjr2 = sd(adj_r2, na.rm = TRUE),
            mean_rmse = mean(rmse, na.rm = TRUE),
            sd_rmse = sd(rmse, na.rm = TRUE),
            mean_rse = mean(rse, na.rm = TRUE),
            sd_rse = sd(rse, na.rm = TRUE))
# r-square -> mean = 0.995, sd = 0.00313
# adj r-square -> mean = 0.992, sd = 0.00501
# rmse -> mean = 1.04, sd = 0.329
# rse -> mean = 1.39, sd = 0.441

# IMPORTANT NOTES below
# note that the rse calculated by myself is not completely equals to the value 
# generated by R itself, but very close. In the CSI report, I'll use the RSE
# generated by R