library(tidyverse)

library(FactoMineR)

library(factoextra)

df <- read_csv("analysis/total_new_convert.csv")

# select the variables

df <- df %>%
  filter(Sample != "C+" & Sample != "C-") %>%
  na.omit()

# calculate the mean value of the kinetics 

df1 <- df %>%
  select(2, 29:31) %>%
  group_by(Sample) %>%
  summarise(k = mean(k), h = mean(h), Xinf = mean(Xinf)) 

# select the structural properties

df2 <- df %>%
  select(2, 5:19) %>% 
  unique() 

# combine and scale

df_new <- full_join(df2, df1) %>%
  select(Sample, Amylose_Con, SSA, SWM, D0.1, D0.5, D0.9, DP6_12, DP13_24, DP25_36, DP37_47, Amylase_Act, Peak_Vis, Trough_Vis,
         Final_Vis, Pasting_Temp, k, h, Xinf) %>%
  remove_rownames() %>%
  column_to_rownames(var = 'Sample') %>%
  scale()

#### ncp=6 #### 

# compute PCA

res.pca <- PCA(df_new, 
               ncp = 6,
               scale.unit = TRUE, 
               quanti.sup = 12:18, # add RVA and kinetics as supplementary data (illustrative data)
               graph = FALSE)

summary(res.pca)

# scree plot

fviz_eig(res.pca)

#### HCPC ####

# Compute hierarchical clustering on principal components





res.hcpc3$desc.var$quanti

res.hcpc4$desc.var$quanti

res.hcpc5$desc.var$quanti

res.hcpc6$desc.var$quanti

res.hcpc7$desc.var$quanti

res.hcpc10$desc.var$quanti

res.hcpc12$desc.var$quanti

# 2 clusters

res.hcpc2 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 2)

res.hcpc2$desc.var$quanti # contribution of factors  

# 3 clusters

res.hcpc3 <- HCPC(res.pca, graph = TRUE, 
                 consol = TRUE,
                 nb.clust = 3)

res.hcpc3$desc.var$quanti # contribution of factors  

# 4 clusters

res.hcpc4 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 4)

res.hcpc4$desc.var$quanti # contribution of factors  

# 5 clusters

res.hcpc5 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 5)

res.hcpc5$desc.var$quanti # contribution of factors  

# 6 clusters

res.hcpc6 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 6)

res.hcpc6$desc.var$quanti # contribution of factors 

# 7 clusters

res.hcpc7 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 7)

res.hcpc7$desc.var$quanti # contribution of factors 

# 8 clusters

res.hcpc8 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 8)

res.hcpc8$desc.var$quanti # contribution of factors 

# 9 clusters

res.hcpc9 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 9)

res.hcpc9$desc.var$quanti # contribution of factors 

# 10 clusters

res.hcpc10 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 10)

res.hcpc10$desc.var$quanti # contribution of factors 

# 11 clusters

res.hcpc11 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 11)

res.hcpc11$desc.var$quanti # contribution of factors 

# 12 clusters

res.hcpc12 <- HCPC(res.pca, graph = TRUE, 
                   consol = TRUE,
                   nb.clust = 12)

res.hcpc12$desc.var$quanti # contribution of factors 

# 13 clusters

res.hcpc13 <- HCPC(res.pca, graph = TRUE, 
                   consol = TRUE,
                   nb.clust = 13)

res.hcpc13$desc.var$quanti # contribution of factors 

#### wait for modification ####

# visualize the dendrogram generated by the hierarchical clustering

fviz_dend(res.hcpc3, 
          cex = 0.7, # label size
          palette = "jco",
          rect = TRUE, rect_fill = TRUE,
          rect_border = "jco",         
          labels_track_height = 0.8)

## the dentrogram suggest 3 clusters solution

# visualize individuals on the principal component map 
# and to color individuals according to the cluster they belong to (factorial map)

fviz_cluster(res.hcpc3,
             repel = FALSE, # avoid label overlapping
             show.clust.cent = TRUE, # show cluster centers
             palette = "jco", 
             ggtheme = theme_minimal(),
             main = "Factor map"
)

# display the original data with cluster assignments

head(res.hcpc3$data.clust, 10) # 3 clusters as an example

## the last column contains the cluster assignments

# save the results of the HCPC into a dataframe

r_hcpc3_s <- res.hcpc3$data.clust %>% # 3 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster3 = clust) 

r_hcpc3 <- r_hcpc3_s %>%
  select(Sample, cluster3)

r_hcpc4_s <- res.hcpc4$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster4 = clust)

r_hcpc4 <- r_hcpc4_s %>%
  select(Sample, cluster4)

r_hcpc5_s <- res.hcpc5$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster5 = clust)

r_hcpc5 <- r_hcpc5_s %>%
  select(Sample, cluster5)

r_hcpc6_s <- res.hcpc6$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster6 = clust)

r_hcpc6 <- r_hcpc6_s %>%
  select(Sample, cluster6)

r_hcpc7_s <- res.hcpc7$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster7 = clust) 

r_hcpc7 <- r_hcpc7_s %>%
  select(Sample, cluster7)

r_hcpc10_s <- res.hcpc10$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster10 = clust) 

r_hcpc10 <- r_hcpc10_s %>%
  select(Sample, cluster10)

r_hcpc12_s <- res.hcpc12$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster12 = clust) 

r_hcpc12 <- r_hcpc12_s %>%
  select(Sample, cluster12)

# combine all the cluster results together to one single dataframe (unscaled values)

df_0 <- full_join(df2, df1) 

r_hcpc_inter <- left_join(df_0, r_hcpc3)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc4) 

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc5)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc6)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc7)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc10)

r_hcpc_all <- left_join(r_hcpc_inter, r_hcpc12)

# save the final dataset

write_csv(r_hcpc_all, "analysis/hcpc_ncp6.csv")

# combine all the cluster results together to one single dataframe (scaled values)

r_hcpc_s_inter <- left_join(r_hcpc3_s, r_hcpc4)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc5)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc6)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc7)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc10)

r_hcpc_s_all <- left_join(r_hcpc_s_inter, r_hcpc12)

# save the final dataset

write_csv(r_hcpc_s_all, "analysis/hcpc_scaled_ncp6.csv")

#### calculate the mean value of each factor ####

mean_3c <- r_hcpc_s_all %>%
  group_by(cluster3) %>% # by 3 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_4c <- r_hcpc_s_all %>%
  group_by(cluster4) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_5c <- r_hcpc_s_all %>%
  group_by(cluster5) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_6c <- r_hcpc_s_all %>%
  group_by(cluster6) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_7c <- r_hcpc_s_all %>%
  group_by(cluster7) %>% # by 7 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_10c <- r_hcpc_s_all %>%
  group_by(cluster10) %>% # by 9 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_12c <- r_hcpc_s_all %>%
  group_by(cluster12) %>% # by 10 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

#### histogram for each factor ####

# 3 clusters

mean_3c_gather <- mean_3c %>%
  gather("factor", "mean", -cluster3)

mean_3c_gather %>%
  ggplot(aes(x = cluster3, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 4 clusters

mean_4c_gather <- mean_4c %>%
  gather("factor", "mean", -cluster4)

mean_4c_gather %>%
  ggplot(aes(x = cluster4, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 5 clusters

mean_5c_gather <- mean_5c %>%
  gather("factor", "mean", -cluster5)

mean_5c_gather %>%
  ggplot(aes(x = cluster5, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 6 clusters

mean_6c_gather <- mean_6c %>%
  gather("factor", "mean", -cluster6)

mean_6c_gather %>%
  ggplot(aes(x = cluster6, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 7 clusters

mean_7c_gather <- mean_7c %>%
  gather("factor", "mean", -cluster7)

mean_7c_gather %>%
  ggplot(aes(x = cluster7, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 10 clusters

mean_10c_gather <- mean_10c %>%
  gather("factor", "mean", -cluster10)

mean_10c_gather %>%
  ggplot(aes(x = cluster10, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 12 clusters

mean_12c_gather <- mean_12c %>%
  gather("factor", "mean", -cluster12)

mean_12c_gather %>%
  ggplot(aes(x = cluster12, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)


#### anova test for each factor ####

AOV_Output <- aov(SSA ~ cluster3, data = r_hcpc_all)
summary(AOV_Output)

TukeyHSD(AOV_Output)



#### ncp=9 #### 

# compute PCA

res.pca <- PCA(df_new, 
               ncp = 9,
               scale.unit = TRUE, 
               quanti.sup = 12:14, 
               graph = FALSE)

summary(res.pca)

# scree plot

fviz_eig(res.pca)

#### HCPC ####

# Compute hierarchical clustering on principal components

# 4 clusters

res.hcpc4 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 4)

# 5 clusters

res.hcpc5 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 5)

# 6 clusters

res.hcpc6 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 6)

# 8 clusters

res.hcpc8 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 8)

# 9 clusters

res.hcpc9 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 9)

# 11 clusters

res.hcpc11 <- HCPC(res.pca, graph = TRUE, 
                   consol = TRUE,
                   nb.clust = 11)

# 14 clusters

res.hcpc14 <- HCPC(res.pca, graph = TRUE, 
                   consol = TRUE,
                   nb.clust = 14)

# visualize the dendrogram generated by the hierarchical clustering

fviz_dend(res.hcpc14, 
          cex = 0.7, # label size
          palette = "jco",
          rect = TRUE, rect_fill = TRUE,
          rect_border = "jco",         
          labels_track_height = 0.8)

## the dentrogram suggest 3 clusters solution

# visualize individuals on the principal component map 
# and to color individuals according to the cluster they belong to (factorial map)

fviz_cluster(res.hcpc14,
             repel = FALSE, # avoid label overlapping
             show.clust.cent = TRUE, # show cluster centers
             # palette = "jco", 
             ggtheme = theme_minimal(),
             main = "Factor map"
)

# display the original data with cluster assignments

head(res.hcpc3$data.clust, 10) # 3 clusters as an example

## the last column contains the cluster assignments

# save the results of the HCPC into a dataframe

r_hcpc4_s <- res.hcpc4$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster4 = clust)

r_hcpc4 <- r_hcpc4_s %>%
  select(Sample, cluster4)

r_hcpc5_s <- res.hcpc5$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster5 = clust)

r_hcpc5 <- r_hcpc5_s %>%
  select(Sample, cluster5)

r_hcpc6_s <- res.hcpc6$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster6 = clust)

r_hcpc6 <- r_hcpc6_s %>%
  select(Sample, cluster6)

r_hcpc8_s <- res.hcpc8$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster8 = clust) 

r_hcpc8 <- r_hcpc8_s %>%
  select(Sample, cluster8)

r_hcpc9_s <- res.hcpc9$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster9 = clust) 

r_hcpc9 <- r_hcpc9_s %>%
  select(Sample, cluster9)

r_hcpc11_s <- res.hcpc11$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster11 = clust) 

r_hcpc11 <- r_hcpc11_s %>%
  select(Sample, cluster11)

r_hcpc14_s <- res.hcpc14$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster14 = clust) 

r_hcpc14 <- r_hcpc14_s %>%
  select(Sample, cluster14)

# combine all the cluster results together to one single dataframe (unscaled values)

df_0 <- full_join(df2, df1) 

r_hcpc_inter <- left_join(df_0, r_hcpc4)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc5)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc6)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc8)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc9)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc11)

r_hcpc_all <- left_join(r_hcpc_inter, r_hcpc14)

# save the final dataset

write_csv(r_hcpc_all, "analysis/hcpc_ncp9.csv")

# combine all the cluster results together to one single dataframe (scaled values)

r_hcpc_s_inter <- left_join(r_hcpc4_s, r_hcpc5)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc6)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc8)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc9)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc11)

r_hcpc_s_all <- left_join(r_hcpc_s_inter, r_hcpc14)

# save the final dataset

write_csv(r_hcpc_s_all, "analysis/hcpc_scaled_ncp9.csv")

#### calculate the mean value of each factor ####

mean_4c <- r_hcpc_s_all %>%
  group_by(cluster4) %>% # by 3 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_5c <- r_hcpc_s_all %>%
  group_by(cluster5) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_6c <- r_hcpc_s_all %>%
  group_by(cluster6) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_8c <- r_hcpc_s_all %>%
  group_by(cluster8) %>% # by 7 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_9c <- r_hcpc_s_all %>%
  group_by(cluster9) %>% # by 9 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_11c <- r_hcpc_s_all %>%
  group_by(cluster11) %>% # by 10 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_14c <- r_hcpc_s_all %>%
  group_by(cluster14) %>% # by 10 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

#### histogram for each factor ####

# 4 clusters

mean_4c_gather <- mean_4c %>%
  gather("factor", "mean", -cluster4)

mean_4c_gather %>%
  ggplot(aes(x = cluster4, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 5 clusters

mean_5c_gather <- mean_5c %>%
  gather("factor", "mean", -cluster5)

mean_5c_gather %>%
  ggplot(aes(x = cluster5, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 6 clusters

mean_6c_gather <- mean_6c %>%
  gather("factor", "mean", -cluster6)

mean_6c_gather %>%
  ggplot(aes(x = cluster6, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 8 clusters

mean_8c_gather <- mean_8c %>%
  gather("factor", "mean", -cluster8)

mean_8c_gather %>%
  ggplot(aes(x = cluster8, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 9 clusters

mean_9c_gather <- mean_9c %>%
  gather("factor", "mean", -cluster9)

mean_9c_gather %>%
  ggplot(aes(x = cluster9, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 11 clusters

mean_11c_gather <- mean_11c %>%
  gather("factor", "mean", -cluster11)

mean_11c_gather %>%
  ggplot(aes(x = cluster11, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 14 clusters

mean_14c_gather <- mean_14c %>%
  gather("factor", "mean", -cluster14)

mean_14c_gather %>%
  ggplot(aes(x = cluster14, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

#### anova test for each factor ####

AOV_Output <- aov(SSA ~ cluster3, data = r_hcpc_all)
summary(AOV_Output)

TukeyHSD(AOV_Output)

############################## fin de modification

# variability

res.hcpc2$desc.var$quanti

res.hcpc4$desc.var$quanti

res.hcpc5$desc.var$quanti

res.hcpc6$desc.var$quanti

res.hcpc8$desc.var$quanti

res.hcpc9$desc.var$quanti

res.hcpc11$desc.var$quanti

res.hcpc14$desc.var$quanti

#### ncp=7 #### 

# compute PCA

res.pca <- PCA(df_new, 
               ncp = 7,
               scale.unit = TRUE, 
               quanti.sup = 12:14, 
               graph = FALSE)

summary(res.pca)

# scree plot

fviz_eig(res.pca)

#### HCPC ####

# Compute hierarchical clustering on principal components

# 4 clusters

res.hcpc4 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 4)

# 5 clusters

res.hcpc5 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 5)

# 6 clusters

res.hcpc6 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 6)

# 7 clusters

res.hcpc7 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 7)

# 8 clusters

res.hcpc8 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 8)


# 10 clusters

res.hcpc10 <- HCPC(res.pca, graph = TRUE, 
                   consol = TRUE,
                   nb.clust = 10)

# 12 clusters

res.hcpc12 <- HCPC(res.pca, graph = TRUE, 
                   consol = TRUE,
                   nb.clust = 12)

# visualize the dendrogram generated by the hierarchical clustering

fviz_dend(res.hcpc14, 
          cex = 0.7, # label size
          palette = "jco",
          rect = TRUE, rect_fill = TRUE,
          rect_border = "jco",         
          labels_track_height = 0.8)

## the dentrogram suggest 3 clusters solution

# visualize individuals on the principal component map 
# and to color individuals according to the cluster they belong to (factorial map)

fviz_cluster(res.hcpc4,
             repel = FALSE, # avoid label overlapping
             show.clust.cent = TRUE, # show cluster centers
             # palette = "jco", 
             ggtheme = theme_minimal(),
             main = "Factor map"
)

# display the original data with cluster assignments

head(res.hcpc3$data.clust, 10) # 3 clusters as an example

## the last column contains the cluster assignments

# save the results of the HCPC into a dataframe

r_hcpc4_s <- res.hcpc4$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster4 = clust)

r_hcpc4 <- r_hcpc4_s %>%
  select(Sample, cluster4)

r_hcpc5_s <- res.hcpc5$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster5 = clust)

r_hcpc5 <- r_hcpc5_s %>%
  select(Sample, cluster5)

r_hcpc6_s <- res.hcpc6$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster6 = clust)

r_hcpc6 <- r_hcpc6_s %>%
  select(Sample, cluster6)

r_hcpc7_s <- res.hcpc7$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster7 = clust) 

r_hcpc7 <- r_hcpc7_s %>%
  select(Sample, cluster7)

r_hcpc8_s <- res.hcpc8$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster8 = clust) 

r_hcpc8 <- r_hcpc8_s %>%
  select(Sample, cluster8)

r_hcpc10_s <- res.hcpc10$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster10 = clust) 

r_hcpc10 <- r_hcpc10_s %>%
  select(Sample, cluster10)

r_hcpc12_s <- res.hcpc12$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster12 = clust) 

r_hcpc12 <- r_hcpc12_s %>%
  select(Sample, cluster12)

# combine all the cluster results together to one single dataframe (unscaled values)

df_0 <- full_join(df2, df1) 

r_hcpc_inter <- left_join(df_0, r_hcpc4)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc5)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc6)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc7)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc8)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc10)

r_hcpc_all <- left_join(r_hcpc_inter, r_hcpc12)

# save the final dataset

write_csv(r_hcpc_all, "analysis/hcpc_ncp7.csv")

# combine all the cluster results together to one single dataframe (scaled values)

r_hcpc_s_inter <- left_join(r_hcpc4_s, r_hcpc5)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc6)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc7)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc8)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc10)

r_hcpc_s_all <- left_join(r_hcpc_s_inter, r_hcpc12)

# save the final dataset

write_csv(r_hcpc_s_all, "analysis/hcpc_scaled_ncp7.csv")

#### calculate the mean value of each factor ####

mean_4c <- r_hcpc_s_all %>%
  group_by(cluster4) %>% # by 3 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_5c <- r_hcpc_s_all %>%
  group_by(cluster5) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_6c <- r_hcpc_s_all %>%
  group_by(cluster6) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_7c <- r_hcpc_s_all %>%
  group_by(cluster7) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_8c <- r_hcpc_s_all %>%
  group_by(cluster8) %>% # by 7 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_10c <- r_hcpc_s_all %>%
  group_by(cluster10) %>% # by 9 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_12c <- r_hcpc_s_all %>%
  group_by(cluster12) %>% # by 10 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

#### histogram for each factor ####

# 4 clusters

mean_4c_gather <- mean_4c %>%
  gather("factor", "mean", -cluster4)

mean_4c_gather %>%
  ggplot(aes(x = cluster4, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 5 clusters

mean_5c_gather <- mean_5c %>%
  gather("factor", "mean", -cluster5)

mean_5c_gather %>%
  ggplot(aes(x = cluster5, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 6 clusters

mean_6c_gather <- mean_6c %>%
  gather("factor", "mean", -cluster6)

mean_6c_gather %>%
  ggplot(aes(x = cluster6, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 7 clusters

mean_7c_gather <- mean_7c %>%
  gather("factor", "mean", -cluster7)

mean_7c_gather %>%
  ggplot(aes(x = cluster7, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 8 clusters

mean_8c_gather <- mean_8c %>%
  gather("factor", "mean", -cluster8)

mean_8c_gather %>%
  ggplot(aes(x = cluster8, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 10 clusters

mean_10c_gather <- mean_10c %>%
  gather("factor", "mean", -cluster10)

mean_10c_gather %>%
  ggplot(aes(x = cluster10, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 12 clusters

mean_12c_gather <- mean_12c %>%
  gather("factor", "mean", -cluster12)

mean_12c_gather %>%
  ggplot(aes(x = cluster12, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)


#### anova test for each factor ####

AOV_Output <- aov(SSA ~ cluster3, data = r_hcpc_all)
summary(AOV_Output)

TukeyHSD(AOV_Output)

# variability

res.hcpc4$desc.var$quanti

res.hcpc5$desc.var$quanti

res.hcpc6$desc.var$quanti

res.hcpc7$desc.var$quanti

res.hcpc8$desc.var$quanti

res.hcpc10$desc.var$quanti

res.hcpc12$desc.var$quanti

#### ncp=8 #### 

# compute PCA

res.pca <- PCA(df_new, 
               ncp = 9,
               scale.unit = TRUE, 
               quanti.sup = 12:14, 
               graph = FALSE)

summary(res.pca)

# scree plot

fviz_eig(res.pca)

#### HCPC ####

# Compute hierarchical clustering on principal components

# 4 clusters

res.hcpc3 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 3)

# 5 clusters

res.hcpc5 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 5)

# 6 clusters

res.hcpc6 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 6)

# 10 clusters

res.hcpc10 <- HCPC(res.pca, graph = TRUE, 
                   consol = TRUE,
                   nb.clust = 10)

# 12 clusters

res.hcpc12 <- HCPC(res.pca, graph = TRUE, 
                   consol = TRUE,
                   nb.clust = 12)

# visualize the dendrogram generated by the hierarchical clustering

fviz_dend(res.hcpc14, 
          cex = 0.7, # label size
          palette = "jco",
          rect = TRUE, rect_fill = TRUE,
          rect_border = "jco",         
          labels_track_height = 0.8)

## the dentrogram suggest 3 clusters solution

# visualize individuals on the principal component map 
# and to color individuals according to the cluster they belong to (factorial map)

fviz_cluster(res.hcpc4,
             repel = FALSE, # avoid label overlapping
             show.clust.cent = TRUE, # show cluster centers
             palette = "jco",
             ggtheme = theme_minimal(),
             main = "Factor map"
)

# display the original data with cluster assignments

head(res.hcpc3$data.clust, 10) # 3 clusters as an example

## the last column contains the cluster assignments

# save the results of the HCPC into a dataframe

r_hcpc3_s <- res.hcpc3$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster3 = clust)

r_hcpc3 <- r_hcpc3_s %>%
  select(Sample, cluster3)

r_hcpc5_s <- res.hcpc5$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster5 = clust)

r_hcpc5 <- r_hcpc5_s %>%
  select(Sample, cluster5)

r_hcpc6_s <- res.hcpc6$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster6 = clust)

r_hcpc6 <- r_hcpc6_s %>%
  select(Sample, cluster6)

r_hcpc10_s <- res.hcpc10$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster10 = clust) 

r_hcpc10 <- r_hcpc10_s %>%
  select(Sample, cluster10)

r_hcpc12_s <- res.hcpc12$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster12 = clust) 

r_hcpc12 <- r_hcpc12_s %>%
  select(Sample, cluster12)

# combine all the cluster results together to one single dataframe (unscaled values)

df_0 <- full_join(df2, df1) 

r_hcpc_inter <- left_join(df_0, r_hcpc3)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc5)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc6)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc10)

r_hcpc_all <- left_join(r_hcpc_inter, r_hcpc12)

# save the final dataset

write_csv(r_hcpc_all, "analysis/hcpc_ncp8.csv")

# combine all the cluster results together to one single dataframe (scaled values)

r_hcpc_s_inter <- left_join(r_hcpc3_s, r_hcpc5)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc6)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc10)

r_hcpc_s_all <- left_join(r_hcpc_s_inter, r_hcpc12)

# save the final dataset

write_csv(r_hcpc_s_all, "analysis/hcpc_scaled_ncp8.csv")

#### calculate the mean value of each factor ####

mean_3c <- r_hcpc_s_all %>%
  group_by(cluster3) %>% # by 3 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_5c <- r_hcpc_s_all %>%
  group_by(cluster5) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_6c <- r_hcpc_s_all %>%
  group_by(cluster6) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_10c <- r_hcpc_s_all %>%
  group_by(cluster10) %>% # by 9 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_12c <- r_hcpc_s_all %>%
  group_by(cluster12) %>% # by 10 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

#### histogram for each factor ####

# 3 clusters

mean_3c_gather <- mean_3c %>%
  gather("factor", "mean", -cluster3)

mean_3c_gather %>%
  ggplot(aes(x = cluster3, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 5 clusters

mean_5c_gather <- mean_5c %>%
  gather("factor", "mean", -cluster5)

mean_5c_gather %>%
  ggplot(aes(x = cluster5, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 6 clusters

mean_6c_gather <- mean_6c %>%
  gather("factor", "mean", -cluster6)

mean_6c_gather %>%
  ggplot(aes(x = cluster6, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 10 clusters

mean_10c_gather <- mean_10c %>%
  gather("factor", "mean", -cluster10)

mean_10c_gather %>%
  ggplot(aes(x = cluster10, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 12 clusters

mean_12c_gather <- mean_12c %>%
  gather("factor", "mean", -cluster12)

mean_12c_gather %>%
  ggplot(aes(x = cluster12, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)


#### anova test for each factor ####

AOV_Output <- aov(SSA ~ cluster3, data = r_hcpc_all)
summary(AOV_Output)

TukeyHSD(AOV_Output)

# variability

res.hcpc3$desc.var$quanti

res.hcpc5$desc.var$quanti

res.hcpc6$desc.var$quanti

res.hcpc10$desc.var$quanti

res.hcpc12$desc.var$quanti

#### correlation matrix ####

ncp9 <- read_csv("analysis/hcpc_ncp9.csv")

# select cluster 3 under 11clusters

cluster11_3 <- ncp9 %>%
  filter(cluster11 == 3)

# select cluster 11 under 11clusters

cluster11_11 <- ncp9 %>%
  filter(cluster11 == 11)

# correlations 

library("PerformanceAnalytics")

cluster_11_3_s <- cluster11_3 %>%
  select(2:15)

chart.Correlation(cluster_11_3_s, histogram=TRUE, pch=19)

cluster_11_11_s <- cluster11_11 %>%
  select(2:15)

# nothing interesting found...

# corrplot

library(corrplot)

cor_result <- cor(cluster_11_3_s, use = "complete.obs") # noted that cluster_11_3_s is with similar amylose content

correlation <- corrplot(cor_result, method = "number", type = "lower",
                        tl.cex = 0.5, number.cex = 0.5) 

cor_result <- cor(cluster_11_11_s, use = "complete.obs") # noted that cluster_11_3_s is with similar amylose content

correlation <- corrplot(cor_result, method = "number", type = "lower",
                        tl.cex = 0.5, number.cex = 0.5) 
