library(tidyverse)

library(FactoMineR)

library(factoextra)

df <- read_csv("analysis/total_new_convert.csv")

# select the variables

df <- df %>%
  filter(Sample != "C+" & Sample != "C-") %>%
  na.omit()

# calculate the mean value of the kinetics 

df1 <- df %>%
  select(2, 29:31) %>%
  group_by(Sample) %>%
  summarise(k = mean(k), h = mean(h), Xinf = mean(Xinf)) 

# select the structural properties

df2 <- df %>%
  select(2, 5:19) %>% 
  unique()

# combine and scale

df_new <- full_join(df2, df1) %>%
  remove_rownames() %>%
  column_to_rownames(var = 'Sample') %>%
  scale()

# compute PCA

res.pca <- PCA(df_new, 
               ncp = 8, 
               scale.unit = TRUE, 
               quanti.sup = 16:18, 
               graph = FALSE)

summary(res.pca)

#### HCPC ####

# Compute hierarchical clustering on principal components

# 3 clusters

res.hcpc3 <- HCPC(res.pca, graph = TRUE, 
                 consol = TRUE,
                 nb.clust = 3)

# 4 clusters

res.hcpc4 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 4)

# 7 clusters

res.hcpc7 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 7)

# 9 clusters

res.hcpc9 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 9)

# 10 clusters

res.hcpc10 <- HCPC(res.pca, graph = TRUE, 
                  consol = TRUE,
                  nb.clust = 10)

# visualize the dendrogram generated by the hierarchical clustering

fviz_dend(res.hcpc, 
          cex = 0.7, # label size
          palette = "jco",
          rect = TRUE, rect_fill = TRUE,
          rect_border = "jco",         
          labels_track_height = 0.8)

## the dentrogram suggest 3 clusters solution

# visualize individuals on the principal component map 
# and to color individuals according to the cluster they belong to (factorial map)

fviz_cluster(res.hcpc,
             repel = FALSE, # avoid label overlapping
             show.clust.cent = TRUE, # show cluster centers
             palette = "jco", 
             ggtheme = theme_minimal(),
             main = "Factor map"
)

# display the original data with cluster assignments

head(res.hcpc3$data.clust, 10) # 3 clusters as an example

## the last column contains the cluster assignments

# save the results of the HCPC into a dataframe

r_hcpc3_s <- res.hcpc3$data.clust %>% # 3 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster3 = clust) 

r_hcpc3 <- r_hcpc3_s %>%
  select(Sample, cluster3)

r_hcpc4_s <- res.hcpc4$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster4 = clust)

r_hcpc4 <- r_hcpc4_s %>%
  select(Sample, cluster4)

r_hcpc7_s <- res.hcpc7$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster7 = clust) 

r_hcpc7 <- r_hcpc7_s %>%
  select(Sample, cluster7)

r_hcpc9_s <- res.hcpc9$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster9 = clust) 

r_hcpc9 <- r_hcpc9_s %>%
  select(Sample, cluster9)

r_hcpc10_s <- res.hcpc10$data.clust %>% # 4 clusters
  rownames_to_column() %>% # change the row names into column names 
  rename(Sample = rowname, cluster10 = clust) 

r_hcpc10 <- r_hcpc10_s %>%
  select(Sample, cluster10)

# combine all the cluster results together to one single dataframe (unscaled values)

df_0 <- full_join(df2, df1) 

r_hcpc_inter <- left_join(df_0, r_hcpc3)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc4) 

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc7)

r_hcpc_inter <- left_join(r_hcpc_inter, r_hcpc9)

r_hcpc_all <- left_join(r_hcpc_inter, r_hcpc10)

# save the final dataset

write_csv(r_hcpc_all, "analysis/hcpc_results.csv")

# combine all the cluster results together to one single dataframe (scaled values)

r_hcpc_s_inter <- left_join(r_hcpc3_s, r_hcpc4)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc7)

r_hcpc_s_inter <- left_join(r_hcpc_s_inter, r_hcpc9)

r_hcpc_s_all <- left_join(r_hcpc_s_inter, r_hcpc10)

# save the final dataset

write_csv(r_hcpc_s_all, "analysis/hcpc_results_scaled.csv")

#### calculate the mean value of each factor ####

mean_3c <- r_hcpc_s_all %>%
  group_by(cluster3) %>% # by 3 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_4c <- r_hcpc_s_all %>%
  group_by(cluster4) %>% # by 4 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_7c <- r_hcpc_s_all %>%
  group_by(cluster7) %>% # by 7 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_9c <- r_hcpc_s_all %>%
  group_by(cluster9) %>% # by 9 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

mean_10c <- r_hcpc_s_all %>%
  group_by(cluster10) %>% # by 10 clusters
  summarise_if(is.numeric, mean, na.rm = TRUE) 

#### histogram for each factor ####

# 3 clusters

mean_3c_gather <- mean_3c %>%
  gather("factor", "mean", -cluster3)

mean_3c_gather %>%
  ggplot(aes(x = cluster3, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 4 clusters

mean_4c_gather <- mean_4c %>%
  gather("factor", "mean", -cluster4)

mean_4c_gather %>%
  ggplot(aes(x = cluster4, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 7 clusters

mean_7c_gather <- mean_7c %>%
  gather("factor", "mean", -cluster7)

mean_7c_gather %>%
  ggplot(aes(x = cluster7, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 9 clusters

mean_9c_gather <- mean_9c %>%
  gather("factor", "mean", -cluster9)

mean_9c_gather %>%
  ggplot(aes(x = cluster9, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)

# 10 clusters

mean_10c_gather <- mean_10c %>%
  gather("factor", "mean", -cluster10)

mean_10c_gather %>%
  ggplot(aes(x = cluster10, y = mean)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~factor)


#### anova test for each factor ####

AOV_Output <- aov(SSA ~ cluster3, data = r_hcpc_all)
summary(AOV_Output)

TukeyHSD(AOV_Output)
